### ISSUE TITLE
EchoRequest: The operation has timed out

### ISSUE THREAD

**Issue by bestia-dev** [MPrtenjak/SLOTax#2]
Download-al sem zadnji EXE. Sem ga zagnal. 
Izbral sem moje digitalno potrdilo "Tesno podjetje..:".
Drugo sem pustil vse nespremenjeno: EchoRequest, Tip:Test, Timeout: 2sec
Kliknil sem "Pošlji na FURS".
In dobim napako:

The operation has timed out

Kaj delam narobe?

**Comment by bestia-dev** [comment]
Možno je, da moj firewall ne dovoli komunikacije na portu 9002.
Bom prvo to preveril.

**Comment by MPrtenjak** [comment]
Da, preverite požarni zid
