### ISSUE TITLE
Ponovno pošiljanje spremenjenega računa

### ISSUE THREAD

**Issue by etbin** [MPrtenjak/SLOTax#3]
Spoštovani
Ali je slučajno kdo zaznal kakšen problem , pri ponovnem pošiljanju računa v potrditev zaradi tehnične napake (preimer xml -a iz vprašanj in odgovorov št 301) 	za  </fu:ReferenceInvoice>je dodana samo ta vrstica: <fu:SpecialNotes>T-CHSEQ#1DT2016-01-02T08:18:24;</fu:SpecialNotes>

Primer xml datoteke
<fu:Invoice>
	<fu:TaxNumber>10033530</fu:TaxNumber>
	<fu:IssueDateTime>2016-01-02T08:16:11</fu:IssueDateTime>
	<fu:NumberingStructure>B</fu:NumberingStructure>
	<fu:InvoiceIdentifier>
		<fu:BusinessPremiseID>TRGOVINA1</fu:BusinessPremiseID>
		<fu:ElectronicDeviceID>BLAG2</fu:ElectronicDeviceID>
		<fu:InvoiceNumber>145</fu:InvoiceNumber>
	</fu:InvoiceIdentifier>
	<fu:InvoiceAmount>67.32</fu:InvoiceAmount>
	<fu:PaymentAmount>67.32</fu:PaymentAmount>
	<fu:TaxesPerSeller>
	<fu:VAT>
		<fu:TaxRate>22.00</fu:TaxRate>
		<fu:TaxableAmount>55.18</fu:TaxableAmount>
		<fu:TaxAmount>12.14</fu:TaxAmount>
	</fu:VAT>
	</fu:TaxesPerSeller>
	<fu:OperatorTaxNumber>12345678</fu:OperatorTaxNumber>
	<fu:ProtectedID>9369b6837aae11940654e5cbf82ddb54</fu:ProtectedID>
	<fu:ReferenceInvoice>
		<fu:ReferenceInvoiceIdentifier>
			<fu:BusinessPremiseID>TRGOVINA1</fu:BusinessPremiseID>
			<fu:ElectronicDeviceID>BLAG2</fu:ElectronicDeviceID>
			<fu:InvoiceNumber>145</fu:InvoiceNumber>
		</fu:ReferenceInvoiceIdentifier>
		<fu:ReferenceInvoiceIssueDateTime>2016-01-02T08:16:11</fu:ReferenceInvoiceIssueDateTime>
	</fu:ReferenceInvoice>
	<fu:SpecialNotes>T-CHSEQ#1DT2016-01-02T08:18:24;</fu:SpecialNotes>
</fu:Invoice>

**Comment by MPrtenjak** [comment]
Pozdravljeni,

Ne, nimam poročil o problemih. Kaj pa naj bi bilo? Kakšna napaka?

**Comment by etbin** [comment]
V primeru da se pošilja tehnični popravek storno računa je xml  sledeč.

fu:Invoice
fu:TaxNumber10033530</fu:TaxNumber>
fu:IssueDateTime2016-01-02T08:16:11</fu:IssueDateTime>
fu:NumberingStructureB</fu:NumberingStructure>
fu:InvoiceIdentifier
fu:BusinessPremiseIDTRGOVINA1</fu:BusinessPremiseID>
fu:ElectronicDeviceIDBLAG2</fu:ElectronicDeviceID>
fu:InvoiceNumber145</fu:InvoiceNumber>
</fu:InvoiceIdentifier>
fu:InvoiceAmount67.32</fu:InvoiceAmount>
fu:PaymentAmount67.32</fu:PaymentAmount>
fu:TaxesPerSeller
fu:VAT
fu:TaxRate22.00</fu:TaxRate>
fu:TaxableAmount55.18</fu:TaxableAmount>
fu:TaxAmount12.14</fu:TaxAmount>
</fu:VAT>
</fu:TaxesPerSeller>
fu:OperatorTaxNumber12345678</fu:OperatorTaxNumber>
fu:ProtectedID9369b6837aae11940654e5cbf82ddb54</fu:ProtectedID>
fu:ReferenceInvoice
fu:ReferenceInvoiceIdentifier
fu:BusinessPremiseIDTRGOVINA1</fu:BusinessPremiseID>
fu:ElectronicDeviceIDBLAG2</fu:ElectronicDeviceID>
fu:InvoiceNumber135</fu:InvoiceNumber>
</fu:ReferenceInvoiceIdentifier>
fu:ReferenceInvoiceIssueDateTime2016-01-01T08:18:12</fu:ReferenceInvoiceIssueDateTime>
</fu:ReferenceInvoice>
fu:ReferenceInvoice
fu:ReferenceInvoiceIdentifier
fu:BusinessPremiseIDTRGOVINA1</fu:BusinessPremiseID>
fu:ElectronicDeviceIDBLAG2</fu:ElectronicDeviceID>
fu:InvoiceNumber145</fu:InvoiceNumber>
</fu:ReferenceInvoiceIdentifier>
fu:ReferenceInvoiceIssueDateTime2016-01-02T08:16:11</fu:ReferenceInvoiceIssueDateTime>
</fu:ReferenceInvoice>
fu:SpecialNotesT-CHSEQ#1DT2016-01-02T08:18:24;</fu:SpecialNotes>
</fu:Invoice>

**Comment by etbin** [comment]
pomeni da se podatki o dveh ali večih predhodnih računih v datoteko s podatki o računu vpišejo na način kot je navedeno spodaj:
fu:ReferenceInvoice
fu:ReferenceInvoiceIdentifier
fu:BusinessPremiseIDTRGOVINA1</fu:BusinessPremiseID>
fu:ElectronicDeviceIDBLAG2</fu:ElectronicDeviceID>
fu:InvoiceNumber135</fu:InvoiceNumber>
</fu:ReferenceInvoiceIdentifier>
fu:ReferenceInvoiceIssueDateTime2016-01-01T08:18:12</fu:ReferenceInvoiceIssueDateTime>
</fu:ReferenceInvoice>
fu:ReferenceInvoice
fu:ReferenceInvoiceIdentifier
fu:BusinessPremiseIDTRGOVINA1</fu:BusinessPremiseID>
fu:ElectronicDeviceIDBLAG2</fu:ElectronicDeviceID>
fu:InvoiceNumber145</fu:InvoiceNumber>
</fu:ReferenceInvoiceIdentifier>
fu:ReferenceInvoiceIssueDateTime2016-01-02T08:16:11</fu:ReferenceInvoiceIssueDateTime>
</fu:ReferenceInvoice>

**Comment by MPrtenjak** [comment]
Ja; to so pa že čisto vsebinske zadeve in z mojim SW nimajo zveze...

**Comment by etbin** [comment]
Razumem, vseeno hvala.
